#!/bin/sh
#
# UniFi Video Docker Init
# Copyright (C) 2019 James T. Lee
#
# Starts the unifi-video service and waits for it to exit.
#

trap '/etc/init.d/unifi-video stop' TERM
/etc/init.d/unifi-video start
while /etc/init.d/unifi-video status > /dev/null; do sleep 1 done
